{
 "title": "Transactions Dashboard",
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  {
   "title": "Maximum daily transactions",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT `day`, any(transaction_type) AS transaction_type, any(currency) AS currency, max(total) as maximum\nFROM (\n  SELECT `day`, transaction_type, currency, sumMerge(total) as total\n  FROM `default`.daily_summary\n  WHERE ( `day` >= $__fromTime AND `day` <= $__toTime )\n  GROUP BY `day`, transaction_type, currency\n  )\nGROUP BY `day`\nORDER BY `day` DESC;"
    }
   ]
  },
  {
   "title": "Daily Number of Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT day as \"time\", countMerge(count) as \"Number Of Transactions\" FROM \"default\".\"daily_summary\" WHERE ( time >= $__fromTime AND time <= $__toTime ) GROUP BY day ORDER BY time ASC LIMIT 10000"
    }
   ]
  },
  {
   "title": "Total of transactions",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT transaction_type, currency, sumMerge(total) as total FROM \"default\".\"daily_summary\" GROUP BY transaction_type, currency ORDER BY total DESC LIMIT 1000"
    }
   ]
  },
  {
   "title": "Transactions by Currency",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT countMerge(count) AS value, currency AS label FROM \"default\".\"daily_summary\" GROUP BY currency LIMIT 1000"
    }
   ]
  }
 ]
}