services:
  clickhouse:
    hostname: clickhouse
    container_name: clickhouse-container
    image: clickhouse/clickhouse-server:24.9.2.42
    env_file: 
      - .env
    volumes:
      - ../../volumes/clickhouse/data:/var/lib/clickhouse
      - ../../volumes/clickhouse/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ../../volumes/clickhouse/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ../../volumes/clickhouse/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
    healthcheck:
      test: wget --spider -q 0.0.0.0:8123/ping
      interval: 5s
      timeout: 3s
      retries: 5
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "8123:8123"
      - "19000:9000"

networks:
  default:
    name: pipeline-network