apiVersion: 1
datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    jsonData:
      defaultDatabase: ${CH_SCHEMA}
      port: ${CH_PORT}
      server: ${CH_HOST}
      username: ${CH_USER}
      tlsSkipVerify: true
    secureJsonData:
      password: '${CH_PASSWORD}'
    